dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: js-jx-start
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: jx-go-loops
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: jxknative
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: jxploreserverless
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: react
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
